# Copyright Glen Knowles 2016 - 2019.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}
environment:
  matrix:
    - TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
    - TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 15 2017
    - TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - cmake -G "%GENERATOR%" -A %platform% -T %TOOLSET% ..
  - cmake . -DCMAKE_BUILD_TYPE=%configuration%
        -DCMAKE_INSTALL_PREFIX=publish
        -DINSTALL_LIBS:BOOL=ON
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a dimcli-latest.zip include lib
  - cd ..\..

artifacts:
  - path: build\publish\dimcli-latest.zip
    name: dimcli
    type: zip

test_script:
  - bin\cli --test
