# Copyright Glen Knowles 2016 - 2019.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}

environment:
  matrix:
    - image: Visual Studio 2019
      toolset: v140
    - image: Visual Studio 2017
      toolset: v141
    - image: Visual Studio 2019
      toolset: v142
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - ps: |
      if ($env:APPVEYOR_JOB_NAME.contains("image=Visual Studio 2017")) {
          Invoke-Expression 'cmake -G "Visual Studio 15 2017" -A %platform% -T %toolset% ..'
      } else {
          Invoke-Expression 'cmake -G "Visual Studio 16 2019" -A %platform% -T %toolset% ..'
      }
  - cmake . -DCMAKE_BUILD_TYPE=%configuration%
        -DCMAKE_INSTALL_PREFIX=publish
        -DINSTALL_LIBS:BOOL=ON
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a dimcli-latest.zip include lib
  - cd ..\..

artifacts:
  - path: build\publish\dimcli-latest.zip
    name: dimcli
    type: zip

test_script:
  - bin\cli --test
