# Copyright Glen Knowles 2016 - 2019.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}
environment:
  matrix:
    - CXX: clang++-6.0
      CC: clang-6.0
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - CXX: g++-7
      CC: gcc-7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - CXX: g++-8
      CC: gcc-8
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - CXX: g++-9
      CC: gcc-9
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - CXX: g++-9
      CC: gcc-9
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_COVERAGE: ON
    - TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
    - TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
    - TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
matrix:
  exclude:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: Win32
    - BUILD_COVERAGE: ON
      configuration: Release

platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

for:
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    build_script:
      - md build
      - cd build
      - cmake -G "%GENERATOR%" -A %PLATFORM% -T %TOOLSET% ..
      - cmake . -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DCMAKE_INSTALL_PREFIX=publish
          -DINSTALL_LIBS:BOOL=ON
      - cmake --build . --target install --config %CONFIGURATION%
      - cd publish
      - 7z a dimcli-latest.zip include lib
      - cd ..\..
      - bin\cli --test
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    build_script:
      - export LANG=en_US.UTF-8
      - mkdir -p build && cd build
      - cmake .. -DBUILD_COVERAGE:BOOL=${BUILD_COVERAGE}
      - cmake --build . --config ${CONFIGURATION}
      - ../bin/cli --test

artifacts:
  - path: build\publish\dimcli-latest.zip
    name: dimcli
    type: zip
