# Copyright Glen Knowles 2016 - 2019.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}
environment:
  matrix:
    - TOOLSET: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

for:
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    build_script:
      - md build
      - cd build
      - cmake -G "%GENERATOR%" -A %platform% -T %TOOLSET% ..
      - cmake . -DCMAKE_BUILD_TYPE=%configuration%
          -DCMAKE_INSTALL_PREFIX=publish
          -DINSTALL_LIBS:BOOL=ON
      - cmake --build . --target install --config %configuration%
      - cd publish
      - 7z a dimcli-latest.zip include lib
      - cd ..\..
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        - platform: x64
    build_script:
      - export CXX=g++-7 CC=gcc-7
      - mkdir -p build && cd build
      - cmake .. -DBUILD_COVERAGE:BOOL=${BUILD_COVERAGE}
      - cmake --build .
      - ../bin/cli --test

artifacts:
  - path: build\publish\dimcli-latest.zip
    name: dimcli
    type: zip

test_script:
  - bin\cli --test
