name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    strategy:
      matrix:
        image: [windows-2019]
        platform: [Win32, x64]
        configuration: [Debug, Release]
        toolset: [v140, v141, v142]
    runs-on: ${{matrix.image}}
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        md build 
        cd build
        cmake -G "Visual Studio 16 2019" -A ${{matrix.platform}} -T ${{matrix.toolset}} ..
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --target install --config ${{matrix.configuration}}
        cd publish
        :: 7z a dimcli-latest.zip include lib

    - name: Test
      working-directory: ${{github.workspace}}
      run: bin/cli --test
