name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    strategy:
      matrix:
        image: [windows-2019]
        platform: [Win32, x64]
        configuration: [Debug, Release]
        toolset: [v140, v141, v142]
    runs-on: ${{matrix.image}}
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        md build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A ${{matrix.platform}} -T ${{matrix.toolset}}
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
        cmake --build . --target install --config ${{matrix.configuration}}
        cd publish
        :: 7z a dimcli-latest.zip include lib

    - name: Test
      working-directory: ${{github.workspace}}
      run: '"bin/cli" --test'

  build-ubuntu:
    strategy:
      matrix:
        image: [ubuntu-20.04]
        configuration: [Debug, Release]
        env:
          - CXX=clang++-10 CC=clang-10
          - CXX=clang++-11 CC=clang-11
    runs-on: ${{matrix.image}}
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github-workspace}}
      run: |
        export LANG=en_US.UTF-8 ${{matrix.env}}
        mkdir -p build && cd build
        cmake ..
        cmake --build . --config ${{matrix.configuration}}

    - name: Test
      working-directory: ${{github.workspace}}
      run: '"bin/cli" --test'
